--- #YAML:1.0
name:                Geo-Format-Envisat
version:             0.01
abstract:            Decode ENVISAT and ERS1/ERS2 meta-data
license:             perl
author:              
    - Mark Overmeer
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    File::Basename:                0
    Geo::Point:                    0.08
    IO::Uncompress::AnyUncompress: 2.015
    POSIX:                         0
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
